### PR TITLE
Reorganized Service Question Definitions into types and Exceptions (#580)

### LINKED ISSUE #580: Refactor: Organize the services.question directory into sub-directories
**Describe the solution you'd like**
1. Add a `services.question.types` directory for `QuestionDefinition` and its sub-classes, `QuestionDefinitionBuilder`, and related classes
2. Add a `services.question.exceptions` directory for all custom `*Exception` classes in the question service 

**Done when**
The question service directory is organized into sub-directories, so that the classes under `services.question` are the main service classes (like `QuestionService` + impl)

### PR DESCRIPTION
**Pull request by davidrhallartificialeducation**
### Description
Reorganized Service Question Definitions into types and Exceptions (#580)

### Checklist
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary

### Issue(s)
Fixes #580

### CODE REVIEW

**Comment by davidrhallartificialeducation** [comment]
Mybad guys, deleted my branch and it closed the PR 🤦

**Comment by davidrhallartificialeducation** [comment]
So I'm not sure what's been going on, but I got the browser tests to pass locally, and they would fail the browser PR tests, I reworded a commit and pushed again and the all the tests passed.  Seems like it only fails sometimes so far 66% of the time

**Comment by kendrickt** [comment]
> So I'm not sure what's been going on, but I got the browser tests to pass locally, and then they would fail the browser PR tests, I reworded a commit and force pushed again and the all the tests passed. Seems like it only fails sometimes. So far 66% of the time it has failed, just got it working.

@davidrhallartificialeducation there's a button to rerun the tests. Can you share the failed test logs?

image

**Comment by davidrhallartificialeducation** [comment]
@kendrickt I got this browser test failure in `application_review.test.ts` on my local machine around 50% of the time: 

Screen Shot 2021-04-07 at 6 19 26 PM

I would receive an error in `admin_program_creation.test.ts` 50% of the time in the PR tests

**Comment by kendrickt** [comment]
Have you pulled the latest from main? There was a PR the other day to fix flakey browser tests.

**Comment by kendrickt** [comment]
@davidrhallartificialeducation i'm fixing merge conflicts and merging this in.

**Comment by kendrickt** [comment]
This is re-opened in #711 after fixing large scale merge conflicts with a rebase.

**Pull request closed without merging**
