### PR TITLE
Only use https.

### PR DESCRIPTION
**Pull request by ndmckinley**
### Description
Remove the http path on port 80, leaving only https on port 443.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Related to #742.

### CODE REVIEW

**Comment by ndmckinley** [comment]
(failure unrelated - 500 over at maven's download website - will rerun)

**Review by hmhsu — APPROVED** [review]
Do we need to redirect the request or does it already handled by LB? Or do modern browsers auto-retry on https?

**Comment by ndmckinley** [comment]
I _think_ this will be handled by Amazon but I will check!  :)

**Comment by ndmckinley** [comment]
Thanks - good catch - it would have worked for modern browsers but older ones like to have the explicit redirect, which amazon does not add for you automatically.

**Pull request merged**
