### PR TITLE
Set all legacy entities' lifecycle_stage to 'active'

### PR DESCRIPTION
**Pull request by hmhsu**
### Description
This is to fix columns in db that have null lifecycle_stage.

### CODE REVIEW

**Comment by hmhsu** [comment]
I am trying to find a way to test this locally, but meanwhile would like to get a pre-review to see if I am on the right path.

**Comment by ndmckinley** [comment]
I think this is right / will work.  You can use `bin/deploy-prod` locally to see if it fixes it in prod.

**Comment by hmhsu** [comment]
> I think this is right / will work. You can use `bin/deploy-prod` locally to see if it fixes it in prod.

Deployed and see it works in prod. Assume we want to check this in, right?

**Review by ndmckinley — APPROVED** [review]
Yes please!

**Pull request merged**
