### PR TITLE
Split `Scalar.SELECTION` into two different scalars

### PR DESCRIPTION
**Pull request by carolinedanzi**
### Description
1. Changes `MultiSelectQuestion` to use a scalar `selections`, and `SingleSelectQuestion` uses scalar `selection`
2. This helps us distinguish between the type of data stored - `selection` stores a single choice, whereas `selections` stores a list of choices

**Note: This will essentially  "erase" any existing answers to checkbox questions in prod**

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
#322

### CODE REVIEW

**Review by hmhsu — APPROVED** [review]
Question: is it correct that the only effect is that users lose their existing answers to questions whose scalars are changed?

**Review by hmhsu — APPROVED** [review]
Still LGTM

**Review by natsid — APPROVED** [review]
Thank you!!

**Comment by carolinedanzi** [comment]
> Question: is it correct that the only effect is that users lose their existing answers to questions whose scalars are changed?

That's the only major drawback I can think of, and it only affects checkbox questions (radio and dropdown are unaffected).  Additionally, existing checkbox answers will still be in applicant JSON, but we'll ignore the old `selection` field

**Pull request merged**
