### PR TITLE
Deflake browser tests

### PR DESCRIPTION
**Pull request by hmhsu**
### Description
- Close browser after test
- Compare label string case insensitively when their style change case
- Click the right button to add questions to a program
- Fix a bug in awaiting

### CODE REVIEW

**Review by ndmckinley — APPROVED** [review]
Wow, nice catches, thank you!

**Comment by hmhsu** [comment]
That said, the tests time out, haha.

**Comment by kendrickt** [comment]
(non-blocking) @hmhsu I don't think this is addressed by these changes: https://github.com/seattle-uat/civiform/pull/690/checks?check_run_id=2289905968

is it in scope?

**Comment by hmhsu** [comment]
> (non-blocking) @hmhsu I don't think this is addressed by these changes: https://github.com/seattle-uat/civiform/pull/690/checks?check_run_id=2289905968
> 
> is it in scope?

Yes! There is a bug that we didn't wait for a function that asserts the question state so the next navigation creates a race condition that could caused the assertion to fail, which is what you see in the failure.

**Pull request merged**
