### PR TITLE
Migrate SecurityBrowserTest to playwright

### LINKED ISSUE #699: Migrate SecurityBrowserTest to playwright
There is one selenium browser test file left, [SecurityBrowserTest](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/test/app/SecurityBrowserTest.java). This issue is to migrate it over to [the new browser testing system](https://github.com/seattle-uat/civiform/tree/main/browser-test) that uses playwright.

Done when: SecurityBrowserTest.java is deleted and the functionality it tests is covered by a playwright test

### PR DESCRIPTION
**Pull request by syntapy**
### Description
Migrate last selenium test file

### Checklist
- [ ] Update any test cases for newly update UI
- [ ] Fix inability to log in with idcs in dev environment

### Issue(s)
Fixes #699

### CODE REVIEW

**Comment by bion** [comment]
Hi @syntapy, are you still working on this?

**Comment by syntapy** [comment]
@bion uh yeah I should probably finish this up. I'll revisit it again tomorrow and see if I can get that browser bug fixed

**Comment by bion** [comment]
@syntapy are you planning to pick this back up or is it abandoned?

**Comment by syntapy** [comment]
@bion I think I might give it another shot at some point but not sure I can promise that. Maybe for now its best to close it out

**Pull request closed without merging**
