### PR TITLE
Fixing typo, adding type annotions, and optional chaining.

### PR DESCRIPTION
**Pull request by gwendolyngoetz**
Fixing typo in test. Adding type annotations and a few optional chaining (the ?.) to resolve some syntax errors.

### CODE REVIEW

**Comment by shanemc-goog** [comment]
Suggest the PR title be updated with the material non typo fix.  The typo isn't breaking anything, but ? changes behavior.

**Review by shanemc-goog — APPROVED** [review]

**Review by clouser2 — COMMENTED** [review]
Thanks for fixing this! I have absolutely no idea why CI didn't catch this.

**Comment by shanemc-goog** [comment]
oops mea culpa, I reviewed while a little distracted.  the typo did have a material effect.  Thanks for adding the other change types too.

**Comment by gwendolyngoetz** [comment]
No worries. I labeled things poorly anyway.

**Pull request merged**
