### PR TITLE
Remove redundant html container tag wrapping html document

### LINKED ISSUE #2257: Site renders multiple html tags
**Describe the bug**
When loading a page the application is creating two html tags. We should remove the outer html tag and keep the one with the lang attribute.

Example:

```
<!DOCTYPE html>
<html>
<html lang="en">

...

</html>
</html>
```

### PR DESCRIPTION
**Pull request by th174**
### Description
The html document body was being unnecessarily wrapped in a second html tag in the j2html template. This PR removes the redundant tag.

### Checklist
- [x] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #2257

### CODE REVIEW

**Review by gwendolyngoetz — APPROVED** [review]
I ran the branch and can confirm there are no longer dup html tags.

**Review by bion — APPROVED** [review]

**Comment by th174** [comment]
Oops, I accidentally misclicked Close Pull Request

**Comment by th174** [comment]
I don't have write access, so someone will have to merge this for me.

**Comment by bion** [comment]
> I don't have write access, so someone will have to merge this for me.

@th174 i enabled automerge

**Comment by th174** [comment]
Synced this branch with main

**Comment by bion** [comment]
@th174 it looks like you may have rebased main which is causing the diff to look a lot bigger. iirc the reason that happens is rebasing causes the commits to be recomputed so they get new SHAs, so git thinks you're introducing a lot more changes than you actually are. i find merging main into my working branch to be a little less fraught with these kinds of problems.

to get the cleaner diff back, i recommend

1. `git pull` on your main branch to ensure it's up to date with seattle-uat's main
1. reset your working branch to the commit before you did the rebase
1. merge main into your working branch, push to github

**Comment by th174** [comment]
> @th174 it looks like you may have rebased main which is causing the diff to look a lot bigger. iirc the reason that happens is rebasing causes the commits to be recomputed so they get new SHAs, so git thinks you're introducing a lot more changes than you actually are. i find merging main into my working branch to be a little less fraught with these kinds of problems.
> 
> to get the cleaner diff back, i recommend
> 
> 1. `git pull` on your main branch to ensure it's up to date with seattle-uat's main
> 2. reset your working branch to the commit before you did the rebase
> 3. merge main into your working branch, push to github

Thanks, I synced with main via a merge rather than a rebase this time.

**Comment by bion** [comment]
Looks like this change is breaking some browser tests

**Review by gwendolyngoetz — APPROVED** [review]

**Review by azizova-leyla — APPROVED** [review]

**Pull request merged**
