### PR TITLE
Set existing programs to have empty export

### PR DESCRIPTION
**Pull request by hmhsu**
### Description
Retrofit db column for existing programs.

### CODE REVIEW

**Comment by hmhsu** [comment]
I wonder if this is only for testing purpose, do we need to persist it in db?

**Comment by kendrickt** [comment]
@ndmckinley should the export definitions be persisted? they weren't in the DB before but it seems like they should be. Or are they transiently defined for each request from the admin UI?

**Review by ndmckinley — APPROVED** [review]

**Comment by ndmckinley** [comment]
It's worth persisting them, but they're not currently configurable - I had intended to persist them in the PR where I made them configurable.

**Comment by hmhsu** [comment]
SG. Thanks for the answers. Merging this.

**Pull request merged**
